//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace studentprofiledesign1
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DataEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DataEntities object using the connection string found in the 'DataEntities' section of the application configuration file.
        /// </summary>
        public DataEntities() : base("name=DataEntities", "DataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DataEntities object.
        /// </summary>
        public DataEntities(string connectionString) : base(connectionString, "DataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DataEntities object.
        /// </summary>
        public DataEntities(EntityConnection connection) : base(connection, "DataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<REGISTRATION_TABLE1> REGISTRATION_TABLE1
        {
            get
            {
                if ((_REGISTRATION_TABLE1 == null))
                {
                    _REGISTRATION_TABLE1 = base.CreateObjectSet<REGISTRATION_TABLE1>("REGISTRATION_TABLE1");
                }
                return _REGISTRATION_TABLE1;
            }
        }
        private ObjectSet<REGISTRATION_TABLE1> _REGISTRATION_TABLE1;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the REGISTRATION_TABLE1 EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToREGISTRATION_TABLE1(REGISTRATION_TABLE1 rEGISTRATION_TABLE1)
        {
            base.AddObject("REGISTRATION_TABLE1", rEGISTRATION_TABLE1);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DataModel", Name="REGISTRATION_TABLE1")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class REGISTRATION_TABLE1 : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new REGISTRATION_TABLE1 object.
        /// </summary>
        /// <param name="eNROLLMENT_NO">Initial value of the ENROLLMENT_NO property.</param>
        /// <param name="fATHER_NAME">Initial value of the FATHER_NAME property.</param>
        /// <param name="mOTHER_NAME">Initial value of the MOTHER_NAME property.</param>
        /// <param name="pHONE_NO2">Initial value of the PHONE_NO2 property.</param>
        /// <param name="oCCUPATION">Initial value of the OCCUPATION property.</param>
        /// <param name="oFFICE">Initial value of the OFFICE property.</param>
        /// <param name="pERMANENT_ADDRESS">Initial value of the PERMANENT_ADDRESS property.</param>
        /// <param name="iMAGE">Initial value of the IMAGE property.</param>
        /// <param name="fRIEND1_NAME">Initial value of the FRIEND1_NAME property.</param>
        /// <param name="fRIEND1_CLASS">Initial value of the FRIEND1_CLASS property.</param>
        /// <param name="fRIEND1_COURSE">Initial value of the FRIEND1_COURSE property.</param>
        /// <param name="fRIEND1_ROLL_NO">Initial value of the FRIEND1_ROLL_NO property.</param>
        /// <param name="fRIEND1_PHONE_NO">Initial value of the FRIEND1_PHONE_NO property.</param>
        /// <param name="fRIEND2_NAME">Initial value of the FRIEND2_NAME property.</param>
        /// <param name="fRIEND2_CLASS">Initial value of the FRIEND2_CLASS property.</param>
        /// <param name="fRIEND2_COURSE">Initial value of the FRIEND2_COURSE property.</param>
        /// <param name="fRIEND2_ROLL_NO">Initial value of the FRIEND2_ROLL_NO property.</param>
        /// <param name="fRIEND2_PHONE_NO">Initial value of the FRIEND2_PHONE_NO property.</param>
        /// <param name="pICIMAGE">Initial value of the PICIMAGE property.</param>
        public static REGISTRATION_TABLE1 CreateREGISTRATION_TABLE1(global::System.String eNROLLMENT_NO, global::System.String fATHER_NAME, global::System.String mOTHER_NAME, global::System.String pHONE_NO2, global::System.String oCCUPATION, global::System.String oFFICE, global::System.String pERMANENT_ADDRESS, global::System.String iMAGE, global::System.String fRIEND1_NAME, global::System.String fRIEND1_CLASS, global::System.String fRIEND1_COURSE, global::System.String fRIEND1_ROLL_NO, global::System.String fRIEND1_PHONE_NO, global::System.String fRIEND2_NAME, global::System.String fRIEND2_CLASS, global::System.String fRIEND2_COURSE, global::System.String fRIEND2_ROLL_NO, global::System.String fRIEND2_PHONE_NO, global::System.Byte[] pICIMAGE)
        {
            REGISTRATION_TABLE1 rEGISTRATION_TABLE1 = new REGISTRATION_TABLE1();
            rEGISTRATION_TABLE1.ENROLLMENT_NO = eNROLLMENT_NO;
            rEGISTRATION_TABLE1.FATHER_NAME = fATHER_NAME;
            rEGISTRATION_TABLE1.MOTHER_NAME = mOTHER_NAME;
            rEGISTRATION_TABLE1.PHONE_NO2 = pHONE_NO2;
            rEGISTRATION_TABLE1.OCCUPATION = oCCUPATION;
            rEGISTRATION_TABLE1.OFFICE = oFFICE;
            rEGISTRATION_TABLE1.PERMANENT_ADDRESS = pERMANENT_ADDRESS;
            rEGISTRATION_TABLE1.IMAGE = iMAGE;
            rEGISTRATION_TABLE1.FRIEND1_NAME = fRIEND1_NAME;
            rEGISTRATION_TABLE1.FRIEND1_CLASS = fRIEND1_CLASS;
            rEGISTRATION_TABLE1.FRIEND1_COURSE = fRIEND1_COURSE;
            rEGISTRATION_TABLE1.FRIEND1_ROLL_NO = fRIEND1_ROLL_NO;
            rEGISTRATION_TABLE1.FRIEND1_PHONE_NO = fRIEND1_PHONE_NO;
            rEGISTRATION_TABLE1.FRIEND2_NAME = fRIEND2_NAME;
            rEGISTRATION_TABLE1.FRIEND2_CLASS = fRIEND2_CLASS;
            rEGISTRATION_TABLE1.FRIEND2_COURSE = fRIEND2_COURSE;
            rEGISTRATION_TABLE1.FRIEND2_ROLL_NO = fRIEND2_ROLL_NO;
            rEGISTRATION_TABLE1.FRIEND2_PHONE_NO = fRIEND2_PHONE_NO;
            rEGISTRATION_TABLE1.PICIMAGE = pICIMAGE;
            return rEGISTRATION_TABLE1;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> REGISTER_ID
        {
            get
            {
                return _REGISTER_ID;
            }
            set
            {
                OnREGISTER_IDChanging(value);
                ReportPropertyChanging("REGISTER_ID");
                _REGISTER_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("REGISTER_ID");
                OnREGISTER_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _REGISTER_ID;
        partial void OnREGISTER_IDChanging(Nullable<global::System.Int32> value);
        partial void OnREGISTER_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ENROLLMENT_NO
        {
            get
            {
                return _ENROLLMENT_NO;
            }
            set
            {
                if (_ENROLLMENT_NO != value)
                {
                    OnENROLLMENT_NOChanging(value);
                    ReportPropertyChanging("ENROLLMENT_NO");
                    _ENROLLMENT_NO = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ENROLLMENT_NO");
                    OnENROLLMENT_NOChanged();
                }
            }
        }
        private global::System.String _ENROLLMENT_NO;
        partial void OnENROLLMENT_NOChanging(global::System.String value);
        partial void OnENROLLMENT_NOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PASSWORD
        {
            get
            {
                return _PASSWORD;
            }
            set
            {
                OnPASSWORDChanging(value);
                ReportPropertyChanging("PASSWORD");
                _PASSWORD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PASSWORD");
                OnPASSWORDChanged();
            }
        }
        private global::System.String _PASSWORD;
        partial void OnPASSWORDChanging(global::System.String value);
        partial void OnPASSWORDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CONFIRM_PASSWORD
        {
            get
            {
                return _CONFIRM_PASSWORD;
            }
            set
            {
                OnCONFIRM_PASSWORDChanging(value);
                ReportPropertyChanging("CONFIRM_PASSWORD");
                _CONFIRM_PASSWORD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CONFIRM_PASSWORD");
                OnCONFIRM_PASSWORDChanged();
            }
        }
        private global::System.String _CONFIRM_PASSWORD;
        partial void OnCONFIRM_PASSWORDChanging(global::System.String value);
        partial void OnCONFIRM_PASSWORDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DEPARTMENT
        {
            get
            {
                return _DEPARTMENT;
            }
            set
            {
                OnDEPARTMENTChanging(value);
                ReportPropertyChanging("DEPARTMENT");
                _DEPARTMENT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DEPARTMENT");
                OnDEPARTMENTChanged();
            }
        }
        private global::System.String _DEPARTMENT;
        partial void OnDEPARTMENTChanging(global::System.String value);
        partial void OnDEPARTMENTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CLASS
        {
            get
            {
                return _CLASS;
            }
            set
            {
                OnCLASSChanging(value);
                ReportPropertyChanging("CLASS");
                _CLASS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CLASS");
                OnCLASSChanged();
            }
        }
        private global::System.String _CLASS;
        partial void OnCLASSChanging(global::System.String value);
        partial void OnCLASSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ACADEMIC_YEAR
        {
            get
            {
                return _ACADEMIC_YEAR;
            }
            set
            {
                OnACADEMIC_YEARChanging(value);
                ReportPropertyChanging("ACADEMIC_YEAR");
                _ACADEMIC_YEAR = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ACADEMIC_YEAR");
                OnACADEMIC_YEARChanged();
            }
        }
        private global::System.String _ACADEMIC_YEAR;
        partial void OnACADEMIC_YEARChanging(global::System.String value);
        partial void OnACADEMIC_YEARChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ROLL_NO
        {
            get
            {
                return _ROLL_NO;
            }
            set
            {
                OnROLL_NOChanging(value);
                ReportPropertyChanging("ROLL_NO");
                _ROLL_NO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ROLL_NO");
                OnROLL_NOChanged();
            }
        }
        private Nullable<global::System.Int32> _ROLL_NO;
        partial void OnROLL_NOChanging(Nullable<global::System.Int32> value);
        partial void OnROLL_NOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                OnNAMEChanging(value);
                ReportPropertyChanging("NAME");
                _NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NAME");
                OnNAMEChanged();
            }
        }
        private global::System.String _NAME;
        partial void OnNAMEChanging(global::System.String value);
        partial void OnNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RELIGION
        {
            get
            {
                return _RELIGION;
            }
            set
            {
                OnRELIGIONChanging(value);
                ReportPropertyChanging("RELIGION");
                _RELIGION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RELIGION");
                OnRELIGIONChanged();
            }
        }
        private global::System.String _RELIGION;
        partial void OnRELIGIONChanging(global::System.String value);
        partial void OnRELIGIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> BOD
        {
            get
            {
                return _BOD;
            }
            set
            {
                OnBODChanging(value);
                ReportPropertyChanging("BOD");
                _BOD = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BOD");
                OnBODChanged();
            }
        }
        private Nullable<global::System.DateTime> _BOD;
        partial void OnBODChanging(Nullable<global::System.DateTime> value);
        partial void OnBODChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CATEGORY
        {
            get
            {
                return _CATEGORY;
            }
            set
            {
                OnCATEGORYChanging(value);
                ReportPropertyChanging("CATEGORY");
                _CATEGORY = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CATEGORY");
                OnCATEGORYChanged();
            }
        }
        private global::System.String _CATEGORY;
        partial void OnCATEGORYChanging(global::System.String value);
        partial void OnCATEGORYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CAST
        {
            get
            {
                return _CAST;
            }
            set
            {
                OnCASTChanging(value);
                ReportPropertyChanging("CAST");
                _CAST = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CAST");
                OnCASTChanged();
            }
        }
        private global::System.String _CAST;
        partial void OnCASTChanging(global::System.String value);
        partial void OnCASTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BLOOD_GROUP
        {
            get
            {
                return _BLOOD_GROUP;
            }
            set
            {
                OnBLOOD_GROUPChanging(value);
                ReportPropertyChanging("BLOOD_GROUP");
                _BLOOD_GROUP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BLOOD_GROUP");
                OnBLOOD_GROUPChanged();
            }
        }
        private global::System.String _BLOOD_GROUP;
        partial void OnBLOOD_GROUPChanging(global::System.String value);
        partial void OnBLOOD_GROUPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ADDRESS
        {
            get
            {
                return _ADDRESS;
            }
            set
            {
                OnADDRESSChanging(value);
                ReportPropertyChanging("ADDRESS");
                _ADDRESS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ADDRESS");
                OnADDRESSChanged();
            }
        }
        private global::System.String _ADDRESS;
        partial void OnADDRESSChanging(global::System.String value);
        partial void OnADDRESSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PHONE_NO1
        {
            get
            {
                return _PHONE_NO1;
            }
            set
            {
                OnPHONE_NO1Changing(value);
                ReportPropertyChanging("PHONE_NO1");
                _PHONE_NO1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PHONE_NO1");
                OnPHONE_NO1Changed();
            }
        }
        private global::System.String _PHONE_NO1;
        partial void OnPHONE_NO1Changing(global::System.String value);
        partial void OnPHONE_NO1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EMAIL_ID
        {
            get
            {
                return _EMAIL_ID;
            }
            set
            {
                OnEMAIL_IDChanging(value);
                ReportPropertyChanging("EMAIL_ID");
                _EMAIL_ID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EMAIL_ID");
                OnEMAIL_IDChanged();
            }
        }
        private global::System.String _EMAIL_ID;
        partial void OnEMAIL_IDChanging(global::System.String value);
        partial void OnEMAIL_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AADHAR_NO
        {
            get
            {
                return _AADHAR_NO;
            }
            set
            {
                OnAADHAR_NOChanging(value);
                ReportPropertyChanging("AADHAR_NO");
                _AADHAR_NO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AADHAR_NO");
                OnAADHAR_NOChanged();
            }
        }
        private global::System.String _AADHAR_NO;
        partial void OnAADHAR_NOChanging(global::System.String value);
        partial void OnAADHAR_NOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GENDER
        {
            get
            {
                return _GENDER;
            }
            set
            {
                OnGENDERChanging(value);
                ReportPropertyChanging("GENDER");
                _GENDER = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GENDER");
                OnGENDERChanged();
            }
        }
        private global::System.String _GENDER;
        partial void OnGENDERChanging(global::System.String value);
        partial void OnGENDERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FATHER_NAME
        {
            get
            {
                return _FATHER_NAME;
            }
            set
            {
                OnFATHER_NAMEChanging(value);
                ReportPropertyChanging("FATHER_NAME");
                _FATHER_NAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FATHER_NAME");
                OnFATHER_NAMEChanged();
            }
        }
        private global::System.String _FATHER_NAME;
        partial void OnFATHER_NAMEChanging(global::System.String value);
        partial void OnFATHER_NAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MOTHER_NAME
        {
            get
            {
                return _MOTHER_NAME;
            }
            set
            {
                OnMOTHER_NAMEChanging(value);
                ReportPropertyChanging("MOTHER_NAME");
                _MOTHER_NAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MOTHER_NAME");
                OnMOTHER_NAMEChanged();
            }
        }
        private global::System.String _MOTHER_NAME;
        partial void OnMOTHER_NAMEChanging(global::System.String value);
        partial void OnMOTHER_NAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PHONE_NO2
        {
            get
            {
                return _PHONE_NO2;
            }
            set
            {
                OnPHONE_NO2Changing(value);
                ReportPropertyChanging("PHONE_NO2");
                _PHONE_NO2 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PHONE_NO2");
                OnPHONE_NO2Changed();
            }
        }
        private global::System.String _PHONE_NO2;
        partial void OnPHONE_NO2Changing(global::System.String value);
        partial void OnPHONE_NO2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OCCUPATION
        {
            get
            {
                return _OCCUPATION;
            }
            set
            {
                OnOCCUPATIONChanging(value);
                ReportPropertyChanging("OCCUPATION");
                _OCCUPATION = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OCCUPATION");
                OnOCCUPATIONChanged();
            }
        }
        private global::System.String _OCCUPATION;
        partial void OnOCCUPATIONChanging(global::System.String value);
        partial void OnOCCUPATIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OFFICE
        {
            get
            {
                return _OFFICE;
            }
            set
            {
                OnOFFICEChanging(value);
                ReportPropertyChanging("OFFICE");
                _OFFICE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OFFICE");
                OnOFFICEChanged();
            }
        }
        private global::System.String _OFFICE;
        partial void OnOFFICEChanging(global::System.String value);
        partial void OnOFFICEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PERMANENT_ADDRESS
        {
            get
            {
                return _PERMANENT_ADDRESS;
            }
            set
            {
                OnPERMANENT_ADDRESSChanging(value);
                ReportPropertyChanging("PERMANENT_ADDRESS");
                _PERMANENT_ADDRESS = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PERMANENT_ADDRESS");
                OnPERMANENT_ADDRESSChanged();
            }
        }
        private global::System.String _PERMANENT_ADDRESS;
        partial void OnPERMANENT_ADDRESSChanging(global::System.String value);
        partial void OnPERMANENT_ADDRESSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IMAGE
        {
            get
            {
                return _IMAGE;
            }
            set
            {
                OnIMAGEChanging(value);
                ReportPropertyChanging("IMAGE");
                _IMAGE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IMAGE");
                OnIMAGEChanged();
            }
        }
        private global::System.String _IMAGE;
        partial void OnIMAGEChanging(global::System.String value);
        partial void OnIMAGEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FRIEND1_NAME
        {
            get
            {
                return _FRIEND1_NAME;
            }
            set
            {
                OnFRIEND1_NAMEChanging(value);
                ReportPropertyChanging("FRIEND1_NAME");
                _FRIEND1_NAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FRIEND1_NAME");
                OnFRIEND1_NAMEChanged();
            }
        }
        private global::System.String _FRIEND1_NAME;
        partial void OnFRIEND1_NAMEChanging(global::System.String value);
        partial void OnFRIEND1_NAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FRIEND1_CLASS
        {
            get
            {
                return _FRIEND1_CLASS;
            }
            set
            {
                OnFRIEND1_CLASSChanging(value);
                ReportPropertyChanging("FRIEND1_CLASS");
                _FRIEND1_CLASS = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FRIEND1_CLASS");
                OnFRIEND1_CLASSChanged();
            }
        }
        private global::System.String _FRIEND1_CLASS;
        partial void OnFRIEND1_CLASSChanging(global::System.String value);
        partial void OnFRIEND1_CLASSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FRIEND1_COURSE
        {
            get
            {
                return _FRIEND1_COURSE;
            }
            set
            {
                OnFRIEND1_COURSEChanging(value);
                ReportPropertyChanging("FRIEND1_COURSE");
                _FRIEND1_COURSE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FRIEND1_COURSE");
                OnFRIEND1_COURSEChanged();
            }
        }
        private global::System.String _FRIEND1_COURSE;
        partial void OnFRIEND1_COURSEChanging(global::System.String value);
        partial void OnFRIEND1_COURSEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FRIEND1_ROLL_NO
        {
            get
            {
                return _FRIEND1_ROLL_NO;
            }
            set
            {
                OnFRIEND1_ROLL_NOChanging(value);
                ReportPropertyChanging("FRIEND1_ROLL_NO");
                _FRIEND1_ROLL_NO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FRIEND1_ROLL_NO");
                OnFRIEND1_ROLL_NOChanged();
            }
        }
        private global::System.String _FRIEND1_ROLL_NO;
        partial void OnFRIEND1_ROLL_NOChanging(global::System.String value);
        partial void OnFRIEND1_ROLL_NOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FRIEND1_PHONE_NO
        {
            get
            {
                return _FRIEND1_PHONE_NO;
            }
            set
            {
                OnFRIEND1_PHONE_NOChanging(value);
                ReportPropertyChanging("FRIEND1_PHONE_NO");
                _FRIEND1_PHONE_NO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FRIEND1_PHONE_NO");
                OnFRIEND1_PHONE_NOChanged();
            }
        }
        private global::System.String _FRIEND1_PHONE_NO;
        partial void OnFRIEND1_PHONE_NOChanging(global::System.String value);
        partial void OnFRIEND1_PHONE_NOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FRIEND2_NAME
        {
            get
            {
                return _FRIEND2_NAME;
            }
            set
            {
                OnFRIEND2_NAMEChanging(value);
                ReportPropertyChanging("FRIEND2_NAME");
                _FRIEND2_NAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FRIEND2_NAME");
                OnFRIEND2_NAMEChanged();
            }
        }
        private global::System.String _FRIEND2_NAME;
        partial void OnFRIEND2_NAMEChanging(global::System.String value);
        partial void OnFRIEND2_NAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FRIEND2_CLASS
        {
            get
            {
                return _FRIEND2_CLASS;
            }
            set
            {
                OnFRIEND2_CLASSChanging(value);
                ReportPropertyChanging("FRIEND2_CLASS");
                _FRIEND2_CLASS = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FRIEND2_CLASS");
                OnFRIEND2_CLASSChanged();
            }
        }
        private global::System.String _FRIEND2_CLASS;
        partial void OnFRIEND2_CLASSChanging(global::System.String value);
        partial void OnFRIEND2_CLASSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FRIEND2_COURSE
        {
            get
            {
                return _FRIEND2_COURSE;
            }
            set
            {
                OnFRIEND2_COURSEChanging(value);
                ReportPropertyChanging("FRIEND2_COURSE");
                _FRIEND2_COURSE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FRIEND2_COURSE");
                OnFRIEND2_COURSEChanged();
            }
        }
        private global::System.String _FRIEND2_COURSE;
        partial void OnFRIEND2_COURSEChanging(global::System.String value);
        partial void OnFRIEND2_COURSEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FRIEND2_ROLL_NO
        {
            get
            {
                return _FRIEND2_ROLL_NO;
            }
            set
            {
                OnFRIEND2_ROLL_NOChanging(value);
                ReportPropertyChanging("FRIEND2_ROLL_NO");
                _FRIEND2_ROLL_NO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FRIEND2_ROLL_NO");
                OnFRIEND2_ROLL_NOChanged();
            }
        }
        private global::System.String _FRIEND2_ROLL_NO;
        partial void OnFRIEND2_ROLL_NOChanging(global::System.String value);
        partial void OnFRIEND2_ROLL_NOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FRIEND2_PHONE_NO
        {
            get
            {
                return _FRIEND2_PHONE_NO;
            }
            set
            {
                OnFRIEND2_PHONE_NOChanging(value);
                ReportPropertyChanging("FRIEND2_PHONE_NO");
                _FRIEND2_PHONE_NO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FRIEND2_PHONE_NO");
                OnFRIEND2_PHONE_NOChanged();
            }
        }
        private global::System.String _FRIEND2_PHONE_NO;
        partial void OnFRIEND2_PHONE_NOChanging(global::System.String value);
        partial void OnFRIEND2_PHONE_NOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] PICIMAGE
        {
            get
            {
                return StructuralObject.GetValidValue(_PICIMAGE);
            }
            set
            {
                OnPICIMAGEChanging(value);
                ReportPropertyChanging("PICIMAGE");
                _PICIMAGE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PICIMAGE");
                OnPICIMAGEChanged();
            }
        }
        private global::System.Byte[] _PICIMAGE;
        partial void OnPICIMAGEChanging(global::System.Byte[] value);
        partial void OnPICIMAGEChanged();

        #endregion

    
    }

    #endregion

    
}
